apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapanjai-ingress
  namespace: sapanjai
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: sapanjai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sapanjai-api-service
                port:
                  number: 3000
