apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: junctera-ingress
  namespace: junctera
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: junctera.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: junctera-api-service
                port:
                  number: 3000
