// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit-logs"
                ],
                "summary": "Query audit logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max results (1-100, default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_module_auditlog.LogResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "INVALID_CREDENTIALS",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "TOO_MANY_ATTEMPTS",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccessToken\u003e",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.LogoutResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate a refresh token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.TokenResponse"
                        }
                    },
                    "401": {
                        "description": "INVALID_REFRESH_TOKEN / REFRESH_TOKEN_REUSE / REFRESH_TOKEN_EXPIRED",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "Registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_auth.TokenResponse"
                        }
                    },
                    "409": {
                        "description": "EMAIL_TAKEN",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "{ status: \\\"ok\\\", uptime: \u003cseconds\u003e }",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/organizations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "List my organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_module_organization.MembershipResponse"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create an organization",
                "parameters": [
                    {
                        "description": "Organization payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_organization.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_organization.OrgResponse"
                        }
                    },
                    "409": {
                        "description": "SLUG_TAKEN",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Invite a member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Invite payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_organization.InviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_organization.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "FORBIDDEN / LIMIT_EXCEEDED / Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "USER_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "ALREADY_MEMBER",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "List organization members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_module_organization.MemberResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/members/{userId}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Remove a member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member user ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_organization.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "CANNOT_REMOVE_OWNER / FORBIDDEN / Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "MEMBER_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/plans": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "List subscription plans",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_module_subscription.PlanResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rbac/assign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rbac"
                ],
                "summary": "Assign a role to a member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Assignment payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.AssignRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "MEMBER_NOT_FOUND / ROLE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rbac/roles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rbac"
                ],
                "summary": "List roles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_module_rbac.RoleResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rbac"
                ],
                "summary": "Create a role",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Role payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.CreateRoleRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.RoleRowResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/rbac/roles/{roleId}/permissions": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rbac"
                ],
                "summary": "Replace a role's permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Role ID",
                        "name": "roleId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New permission set",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.UpdatePermissionsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_rbac.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "ROLE_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get the organization's subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_subscription.SubscriptionResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/assign": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Assign a subscription plan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Active organization ID",
                        "name": "x-organization-id",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Plan payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_module_subscription.AssignRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_module_subscription.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Missing x-organization-id header",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Not a member of this organization",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_junctera_backend_internal_shared_httpx.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_junctera_backend_internal_shared_httpx.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_module_auditlog.LogResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "organizationId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_module_auth.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "internal_module_auth.LogoutResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_module_auth.RefreshRequest": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "internal_module_auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "displayName": {
                    "type": "string",
                    "minLength": 1
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "internal_module_auth.TokenResponse": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "internal_module_organization.CreateRequest": {
            "type": "object",
            "required": [
                "name",
                "slug"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "slug": {
                    "type": "string",
                    "minLength": 2
                }
            }
        },
        "internal_module_organization.InviteRequest": {
            "type": "object",
            "required": [
                "email",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "member"
                    ]
                }
            }
        },
        "internal_module_organization.MemberResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "joinedAt": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_module_organization.MembershipResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "organization": {
                    "$ref": "#/definitions/internal_module_organization.OrgResponse"
                },
                "organizationId": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_module_organization.OrgResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_module_organization.SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_module_rbac.AssignRoleRequest": {
            "type": "object",
            "required": [
                "roleId",
                "userId"
            ],
            "properties": {
                "roleId": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "internal_module_rbac.CreateRoleRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "minLength": 1
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_module_rbac.PermissionResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "roleId": {
                    "type": "string"
                }
            }
        },
        "internal_module_rbac.RoleResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_module_rbac.PermissionResponse"
                    }
                }
            }
        },
        "internal_module_rbac.RoleRowResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                }
            }
        },
        "internal_module_rbac.SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        },
        "internal_module_rbac.UpdatePermissionsRequest": {
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_module_subscription.AssignRequest": {
            "type": "object",
            "required": [
                "planId"
            ],
            "properties": {
                "planId": {
                    "type": "string"
                }
            }
        },
        "internal_module_subscription.PlanResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "limits": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_module_subscription.SubscriptionResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "customLimits": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "id": {
                    "type": "string"
                },
                "organizationId": {
                    "type": "string"
                },
                "plan": {
                    "$ref": "#/definitions/internal_module_subscription.PlanResponse"
                },
                "planId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "internal_module_subscription.SuccessResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer {token}\" — the JWT access token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Junctera API",
	Description:      "Multi-tenant B2B SaaS platform API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
