apiVersion: v1
kind: ConfigMap
metadata:
  name: junctera-config
  namespace: junctera
data:
  APP_NAME: junctera-api
  APP_ENV: production
  LOG_LEVEL: info
  PORT: "3000"
  JWT_ACCESS_EXPIRES_IN: 15m
  JWT_REFRESH_EXPIRES_IN: "604800"
