apiVersion: v1
kind: ConfigMap
metadata:
  name: sapanjai-config
  namespace: sapanjai
data:
  APP_NAME: sapanjai-api
  APP_ENV: production
  LOG_LEVEL: info
  PORT: "3000"
  JWT_ACCESS_EXPIRES_IN: 15m
  JWT_REFRESH_EXPIRES_IN: "604800"
