// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountActiveMCPKeys = `-- name: AdminCountActiveMCPKeys :one
SELECT count(*) FROM mcp_api_keys
WHERE revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) AdminCountActiveMCPKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveMCPKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountActiveSessions = `-- name: AdminCountActiveSessions :one
SELECT count(*) FROM sessions WHERE is_revoked = false AND expires_at > now()
`

func (q *Queries) AdminCountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountActiveSessionsByUser = `-- name: AdminCountActiveSessionsByUser :one
SELECT count(*) FROM sessions
WHERE user_id = $1 AND is_revoked = false AND expires_at > now()
`

func (q *Queries) AdminCountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountActiveSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAllAuditLogs = `-- name: AdminCountAllAuditLogs :one
SELECT count(*) FROM audit_logs
`

func (q *Queries) AdminCountAllAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAllConnectors = `-- name: AdminCountAllConnectors :one
SELECT count(*) FROM connectors
`

func (q *Queries) AdminCountAllConnectors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllConnectors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAllMCPKeys = `-- name: AdminCountAllMCPKeys :one
SELECT count(*) FROM mcp_api_keys
`

func (q *Queries) AdminCountAllMCPKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllMCPKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAllOrganizations = `-- name: AdminCountAllOrganizations :one

SELECT count(*) FROM organizations
`

// The remaining queries back GET /admin/system/stats. Each is cached
// individually under its own fixed filter key (admin.Service.SystemStats) —
// there is no user-supplied filter, but they still go through
// admin.Service.cachedCount for the same "don't COUNT(*) on every staff
// page load" reason as the paged lists above.
func (q *Queries) AdminCountAllOrganizations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllOrganizations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAllUsers = `-- name: AdminCountAllUsers :one
SELECT count(*) FROM users
`

func (q *Queries) AdminCountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountAuditLogs = `-- name: AdminCountAuditLogs :one
SELECT count(*) FROM audit_logs a
WHERE ($1::uuid IS NULL OR a.organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR a.user_id = $2::uuid)
  AND ($3::text[] IS NULL OR a.action LIKE ANY($3::text[]))
  AND ($4::timestamp IS NULL OR a.created_at >= $4::timestamp)
  AND ($5::timestamp IS NULL OR a.created_at <= $5::timestamp)
`

type AdminCountAuditLogsParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	ActionPatterns []string         `json:"action_patterns"`
	From           pgtype.Timestamp `json:"from"`
	To             pgtype.Timestamp `json:"to"`
}

// Mirrors AdminQueryAuditLogs's WHERE exactly.
func (q *Queries) AdminCountAuditLogs(ctx context.Context, arg AdminCountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountAuditLogs,
		arg.OrganizationID,
		arg.UserID,
		arg.ActionPatterns,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountConnectors = `-- name: AdminCountConnectors :one
SELECT count(*) FROM connectors c
WHERE ($1::uuid IS NULL OR c.organization_id = $1::uuid)
  AND ($2::text IS NULL OR c.type = $2::text)
  AND ($3::text IS NULL OR c.status = $3::text)
  AND ($4::text IS NULL OR c.name ILIKE '%' || $4::text || '%')
`

type AdminCountConnectorsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Type           *string     `json:"type"`
	Status         *string     `json:"status"`
	Search         *string     `json:"search"`
}

// Mirrors AdminListConnectors's WHERE exactly.
func (q *Queries) AdminCountConnectors(ctx context.Context, arg AdminCountConnectorsParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountConnectors,
		arg.OrganizationID,
		arg.Type,
		arg.Status,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountEmailOutboxByStatus = `-- name: AdminCountEmailOutboxByStatus :many
SELECT status, count(*) AS status_count FROM email_outbox GROUP BY status
`

type AdminCountEmailOutboxByStatusRow struct {
	Status      string `json:"status"`
	StatusCount int64  `json:"status_count"`
}

// A rising 'failed' count is the single best early warning that Resend or
// the EMAIL_FROM domain is misconfigured (CLAUDE.md's Background worker
// bullet).
func (q *Queries) AdminCountEmailOutboxByStatus(ctx context.Context) ([]AdminCountEmailOutboxByStatusRow, error) {
	rows, err := q.db.Query(ctx, adminCountEmailOutboxByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCountEmailOutboxByStatusRow
	for rows.Next() {
		var i AdminCountEmailOutboxByStatusRow
		if err := rows.Scan(&i.Status, &i.StatusCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCountMCPKeys = `-- name: AdminCountMCPKeys :one
SELECT count(*) FROM mcp_api_keys k
JOIN users u ON u.id = k.user_id
WHERE ($1::uuid IS NULL OR k.organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR k.user_id = $2::uuid)
  AND ($3::text IS NULL
       OR k.name ILIKE '%' || $3::text || '%'
       OR u.email ILIKE '%' || $3::text || '%')
`

type AdminCountMCPKeysParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Search         *string     `json:"search"`
}

// Mirrors AdminListMCPKeys's WHERE exactly.
func (q *Queries) AdminCountMCPKeys(ctx context.Context, arg AdminCountMCPKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountMCPKeys, arg.OrganizationID, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrganizations = `-- name: AdminCountOrganizations :one
SELECT count(*) FROM organizations o
WHERE ($1::text IS NULL
       OR o.name ILIKE '%' || $1::text || '%'
       OR o.slug ILIKE '%' || $1::text || '%')
`

// Mirrors AdminListOrganizations's WHERE exactly — the pair behind
// admin.Service.cachedCount for GET /admin/organizations.
func (q *Queries) AdminCountOrganizations(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOrganizations, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountOrganizationsSince = `-- name: AdminCountOrganizationsSince :one
SELECT count(*) FROM organizations WHERE created_at >= $1
`

func (q *Queries) AdminCountOrganizationsSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountOrganizationsSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountSubscriptionsByPlan = `-- name: AdminCountSubscriptionsByPlan :one
SELECT count(*) FROM org_subscriptions WHERE plan_id = $1
`

// Backs the PLAN_IN_USE guard on plan delete. plans is referenced by
// org_subscriptions.plan_id with ON DELETE no action (migration 00005), so
// the database would reject the delete anyway — this check exists so the
// API can return a real 409 instead of surfacing that constraint
// violation as a 500.
func (q *Queries) AdminCountSubscriptionsByPlan(ctx context.Context, planID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountSubscriptionsByPlan, planID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT count(*) FROM users u
WHERE ($1::text IS NULL
       OR u.email ILIKE '%' || $1::text || '%'
       OR u.display_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL
       OR ($2::text = 'none' AND u.platform_role IS NULL)
       OR ($2::text <> 'none' AND u.platform_role = $2::text))
  AND ($3::bool IS NULL
       OR ($3::bool AND u.banned_at IS NOT NULL)
       OR (NOT $3::bool AND u.banned_at IS NULL))
`

type AdminCountUsersParams struct {
	Search *string `json:"search"`
	Role   *string `json:"role"`
	Banned *bool   `json:"banned"`
}

// Mirrors AdminListUsers's WHERE exactly.
func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Search, arg.Role, arg.Banned)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCountUsersSince = `-- name: AdminCountUsersSince :one
SELECT count(*) FROM users WHERE created_at >= $1
`

func (q *Queries) AdminCountUsersSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsersSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminCreatePlan = `-- name: AdminCreatePlan :one
INSERT INTO plans (name, limits) VALUES ($1, $2) RETURNING id, name, limits, created_at
`

type AdminCreatePlanParams struct {
	Name   string          `json:"name"`
	Limits json.RawMessage `json:"limits"`
}

// plans.name carries a UNIQUE constraint; a colliding name surfaces as a
// raw constraint-violation error (500), the same tolerance
// subscription.Service.AssignPlan documents for a nonexistent plan id —
// neither the source app nor this one adds a dedicated
// PLAN_NAME_TAKEN code for what is, in a 2-5 person staff console, a
// typo caught on the next attempt.
func (q *Queries) AdminCreatePlan(ctx context.Context, arg AdminCreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, adminCreatePlan, arg.Name, arg.Limits)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
	)
	return i, err
}

const adminDeleteOrganization = `-- name: AdminDeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

// memberships/connectors/mcp_api_keys/org_subscriptions all cascade
// (migrations 00002/00005/00007/00008); audit_logs.organization_id carries
// no FK (00004), so audit rows deliberately survive the org — see
// admin.Service.DeleteOrganization's doc comment. The caller has already
// loaded the org (to check its slug against the confirmation field), so
// there is no existence race worth an :execrows check here.
func (q *Queries) AdminDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminDeleteOrganization, id)
	return err
}

const adminDeletePlan = `-- name: AdminDeletePlan :exec
DELETE FROM plans WHERE id = $1
`

// The caller has already loaded the plan (AdminGetPlanByID, for the 404
// check) and confirmed no org_subscriptions row references it
// (AdminCountSubscriptionsByPlan, for PLAN_IN_USE) before this runs.
func (q *Queries) AdminDeletePlan(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, adminDeletePlan, id)
	return err
}

const adminGetOrganizationByID = `-- name: AdminGetOrganizationByID :one

SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

// Queries backing internal/module/admin, the cross-org platform staff
// console (docs/11-admin-panel.md). Every query here deliberately has NO
// organization_id predicate the way the tenant-facing queries do — that is
// the whole point of /admin, not an oversight. See the module's own
// doc comment for the authorization boundary (RequirePlatformRole, not
// RequireOrg/RequirePermission).
//
// None of these ever select connectors.encrypted_config or
// mcp_api_keys.key_hash; column lists are explicit rather than SELECT *
// specifically to keep it that way as the schema evolves.
func (q *Queries) AdminGetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, adminGetOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const adminGetPlanByID = `-- name: AdminGetPlanByID :one
SELECT id, name, limits, created_at FROM plans WHERE id = $1
`

func (q *Queries) AdminGetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, adminGetPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
	)
	return i, err
}

const adminListConnectors = `-- name: AdminListConnectors :many
SELECT
  c.id, c.organization_id, o.name AS organization_name, c.name, c.type, c.status,
  c.last_health_check_at, c.created_at
FROM connectors c
JOIN organizations o ON o.id = c.organization_id
WHERE ($1::uuid IS NULL OR c.organization_id = $1::uuid)
  AND ($2::text IS NULL OR c.type = $2::text)
  AND ($3::text IS NULL OR c.status = $3::text)
  AND ($4::text IS NULL OR c.name ILIKE '%' || $4::text || '%')
ORDER BY c.created_at ASC
LIMIT $6 OFFSET $5
`

type AdminListConnectorsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Type           *string     `json:"type"`
	Status         *string     `json:"status"`
	Search         *string     `json:"search"`
	Off            int32       `json:"off"`
	Lim            int32       `json:"lim"`
}

type AdminListConnectorsRow struct {
	ID                uuid.UUID        `json:"id"`
	OrganizationID    uuid.UUID        `json:"organization_id"`
	OrganizationName  string           `json:"organization_name"`
	Name              string           `json:"name"`
	Type              string           `json:"type"`
	Status            string           `json:"status"`
	LastHealthCheckAt pgtype.Timestamp `json:"last_health_check_at"`
	CreatedAt         time.Time        `json:"created_at"`
}

// Cross-org connector metadata only — no encrypted_config column in this
// SELECT, ever (docs/11-admin-panel.md §7). Also used, filtered by
// organization_id alone, to populate the connector list nested in
// GET /admin/organizations/:orgId (admin.Service.OrganizationDetail).
func (q *Queries) AdminListConnectors(ctx context.Context, arg AdminListConnectorsParams) ([]AdminListConnectorsRow, error) {
	rows, err := q.db.Query(ctx, adminListConnectors,
		arg.OrganizationID,
		arg.Type,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListConnectorsRow
	for rows.Next() {
		var i AdminListConnectorsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.Name,
			&i.Type,
			&i.Status,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListMCPKeys = `-- name: AdminListMCPKeys :many
SELECT
  k.id, k.organization_id, o.name AS organization_name, k.user_id, u.email AS user_email,
  k.name, k.scopes, k.last_used_at, k.expires_at, k.revoked_at, k.created_at
FROM mcp_api_keys k
JOIN organizations o ON o.id = k.organization_id
JOIN users u ON u.id = k.user_id
WHERE ($1::uuid IS NULL OR k.organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR k.user_id = $2::uuid)
  AND ($3::text IS NULL
       OR k.name ILIKE '%' || $3::text || '%'
       OR u.email ILIKE '%' || $3::text || '%')
ORDER BY k.created_at ASC
LIMIT $5 OFFSET $4
`

type AdminListMCPKeysParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Search         *string     `json:"search"`
	Off            int32       `json:"off"`
	Lim            int32       `json:"lim"`
}

type AdminListMCPKeysRow struct {
	ID               uuid.UUID        `json:"id"`
	OrganizationID   uuid.UUID        `json:"organization_id"`
	OrganizationName string           `json:"organization_name"`
	UserID           uuid.UUID        `json:"user_id"`
	UserEmail        string           `json:"user_email"`
	Name             string           `json:"name"`
	Scopes           []string         `json:"scopes"`
	LastUsedAt       pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	RevokedAt        pgtype.Timestamp `json:"revoked_at"`
	CreatedAt        time.Time        `json:"created_at"`
}

// Cross-org MCP key metadata only — no key_hash column in this SELECT,
// ever (docs/11-admin-panel.md §7). search matches the key's own name or
// its owner's email. Also used, filtered by organization_id alone, to
// populate the MCP key list nested in GET /admin/organizations/:orgId.
func (q *Queries) AdminListMCPKeys(ctx context.Context, arg AdminListMCPKeysParams) ([]AdminListMCPKeysRow, error) {
	rows, err := q.db.Query(ctx, adminListMCPKeys,
		arg.OrganizationID,
		arg.UserID,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListMCPKeysRow
	for rows.Next() {
		var i AdminListMCPKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OrganizationName,
			&i.UserID,
			&i.UserEmail,
			&i.Name,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListOrganizations = `-- name: AdminListOrganizations :many
SELECT
  o.id, o.name, o.slug, o.created_at,
  (SELECT count(*) FROM memberships m WHERE m.organization_id = o.id) AS member_count,
  (SELECT count(*) FROM connectors c WHERE c.organization_id = o.id) AS connector_count,
  (SELECT count(*) FROM mcp_api_keys k WHERE k.organization_id = o.id) AS mcp_key_count,
  p.name AS plan_name
FROM organizations o
LEFT JOIN org_subscriptions s ON s.organization_id = o.id
LEFT JOIN plans p ON p.id = s.plan_id
WHERE ($1::text IS NULL
       OR o.name ILIKE '%' || $1::text || '%'
       OR o.slug ILIKE '%' || $1::text || '%')
ORDER BY o.created_at ASC
LIMIT $3 OFFSET $2
`

type AdminListOrganizationsParams struct {
	Search *string `json:"search"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type AdminListOrganizationsRow struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	CreatedAt      time.Time `json:"created_at"`
	MemberCount    int64     `json:"member_count"`
	ConnectorCount int64     `json:"connector_count"`
	McpKeyCount    int64     `json:"mcp_key_count"`
	PlanName       *string   `json:"plan_name"`
}

// search matches name or slug (case-insensitive substring). member/
// connector/mcp-key counts are correlated subqueries rather than a
// three-way JOIN + GROUP BY, which would multiply the plan row per
// member*connector*key combination. plan_name is NULL for an org with no
// subscription row.
func (q *Queries) AdminListOrganizations(ctx context.Context, arg AdminListOrganizationsParams) ([]AdminListOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, adminListOrganizations, arg.Search, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListOrganizationsRow
	for rows.Next() {
		var i AdminListOrganizationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.MemberCount,
			&i.ConnectorCount,
			&i.McpKeyCount,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT
  u.id, u.email, u.display_name, u.is_verified, u.platform_role, u.banned_at, u.created_at,
  (SELECT count(*) FROM memberships m WHERE m.user_id = u.id) AS org_count
FROM users u
WHERE ($1::text IS NULL
       OR u.email ILIKE '%' || $1::text || '%'
       OR u.display_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL
       OR ($2::text = 'none' AND u.platform_role IS NULL)
       OR ($2::text <> 'none' AND u.platform_role = $2::text))
  AND ($3::bool IS NULL
       OR ($3::bool AND u.banned_at IS NOT NULL)
       OR (NOT $3::bool AND u.banned_at IS NULL))
ORDER BY u.created_at ASC
LIMIT $5 OFFSET $4
`

type AdminListUsersParams struct {
	Search *string `json:"search"`
	Role   *string `json:"role"`
	Banned *bool   `json:"banned"`
	Off    int32   `json:"off"`
	Lim    int32   `json:"lim"`
}

type AdminListUsersRow struct {
	ID           uuid.UUID        `json:"id"`
	Email        string           `json:"email"`
	DisplayName  *string          `json:"display_name"`
	IsVerified   bool             `json:"is_verified"`
	PlatformRole *string          `json:"platform_role"`
	BannedAt     pgtype.Timestamp `json:"banned_at"`
	CreatedAt    time.Time        `json:"created_at"`
	OrgCount     int64            `json:"org_count"`
}

// search matches email or display_name. role is nullable text taking
// 'superadmin', 'support', 'none' (meaning platform_role IS NULL), or NULL
// (no filter) — a single text param rather than a separate bool so the
// three-way choice stays one WHERE clause. banned is a nullable bool.
func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Search,
		arg.Role,
		arg.Banned,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListUsersRow
	for rows.Next() {
		var i AdminListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.IsVerified,
			&i.PlatformRole,
			&i.BannedAt,
			&i.CreatedAt,
			&i.OrgCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPlanBreakdown = `-- name: AdminPlanBreakdown :many
SELECT p.name AS plan_name, count(s.id) AS org_count
FROM plans p
LEFT JOIN org_subscriptions s ON s.plan_id = p.id
GROUP BY p.name
ORDER BY p.name ASC
`

type AdminPlanBreakdownRow struct {
	PlanName string `json:"plan_name"`
	OrgCount int64  `json:"org_count"`
}

// LEFT JOIN so a plan with zero subscribers still shows a 0 row rather
// than disappearing from the breakdown entirely.
func (q *Queries) AdminPlanBreakdown(ctx context.Context) ([]AdminPlanBreakdownRow, error) {
	rows, err := q.db.Query(ctx, adminPlanBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminPlanBreakdownRow
	for rows.Next() {
		var i AdminPlanBreakdownRow
		if err := rows.Scan(&i.PlanName, &i.OrgCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminQueryAuditLogs = `-- name: AdminQueryAuditLogs :many
SELECT
  a.id, a.organization_id, a.user_id, a.action, a.metadata, a.created_at,
  o.name AS organization_name, u.email AS user_email
FROM audit_logs a
LEFT JOIN organizations o ON o.id = a.organization_id
LEFT JOIN users u ON u.id = a.user_id
WHERE ($1::uuid IS NULL OR a.organization_id = $1::uuid)
  AND ($2::uuid IS NULL OR a.user_id = $2::uuid)
  AND ($3::text[] IS NULL OR a.action LIKE ANY($3::text[]))
  AND ($4::timestamp IS NULL OR a.created_at >= $4::timestamp)
  AND ($5::timestamp IS NULL OR a.created_at <= $5::timestamp)
ORDER BY a.created_at DESC
LIMIT $7 OFFSET $6
`

type AdminQueryAuditLogsParams struct {
	OrganizationID pgtype.UUID      `json:"organization_id"`
	UserID         pgtype.UUID      `json:"user_id"`
	ActionPatterns []string         `json:"action_patterns"`
	From           pgtype.Timestamp `json:"from"`
	To             pgtype.Timestamp `json:"to"`
	Off            int32            `json:"off"`
	Lim            int32            `json:"lim"`
}

type AdminQueryAuditLogsRow struct {
	ID               uuid.UUID   `json:"id"`
	OrganizationID   pgtype.UUID `json:"organization_id"`
	UserID           pgtype.UUID `json:"user_id"`
	Action           string      `json:"action"`
	Metadata         []byte      `json:"metadata"`
	CreatedAt        time.Time   `json:"created_at"`
	OrganizationName *string     `json:"organization_name"`
	UserEmail        *string     `json:"user_email"`
}

// Cross-org: unlike QueryAuditLogs (internal/infra/database/queries/auditlog.sql),
// which mandates organization_id as a tenant-isolation guarantee, this one
// deliberately carries no such predicate — see admin.sql's file header.
// Two queries, two guarantees; do not widen QueryAuditLogs to cover this.
//
// action_patterns is a nullable text[] of LIKE patterns: the handler turns
// a bare action into a literal (with '%'/'_' escaped) and a trailing '*'
// into a '<prefix>%' pattern, so "admin.*" matches by prefix while an exact
// action matches by equality (LIKE with no wildcard characters behaves as
// equality). `LIKE ANY (array)` matches if any pattern in the array
// matches.
//
// from/to are nullable naive timestamps — audit_logs.created_at has no time
// zone (see QueryAuditLogs's comment); callers must normalize any RFC3339
// input to UTC before binding here, same as there.
func (q *Queries) AdminQueryAuditLogs(ctx context.Context, arg AdminQueryAuditLogsParams) ([]AdminQueryAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, adminQueryAuditLogs,
		arg.OrganizationID,
		arg.UserID,
		arg.ActionPatterns,
		arg.From,
		arg.To,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminQueryAuditLogsRow
	for rows.Next() {
		var i AdminQueryAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
			&i.OrganizationName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSetOrgCustomLimits = `-- name: AdminSetOrgCustomLimits :execrows

UPDATE org_subscriptions SET custom_limits = $2, updated_at = now() WHERE organization_id = $1
`

type AdminSetOrgCustomLimitsParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	CustomLimits   []byte    `json:"custom_limits"`
}

// The remaining queries back Phase 3's mutation routes
// (docs/11-admin-panel.md, execution plan Phase 3). CountSuperadmins,
// SetUserBan, SetUserPlatformRole, and RevokeAllUserSessions already exist
// (queries/users.sql, queries/sessions.sql) and are reused as-is rather
// than duplicated here.
// Touches only org_subscriptions.custom_limits — deliberately narrower
// than UpsertOrgSubscription (subscriptions.sql), which also rewrites
// plan_id via a full upsert. $2 is nullable: NULL clears back to
// plan-only limits. 0 rows affected means the organization has no
// org_subscriptions row yet (no plan ever assigned) — admin.Service turns
// that into a 404 rather than a silent no-op, since org_subscriptions.plan_id
// is NOT NULL and there is nothing here to attach custom_limits to.
func (q *Queries) AdminSetOrgCustomLimits(ctx context.Context, arg AdminSetOrgCustomLimitsParams) (int64, error) {
	result, err := q.db.Exec(ctx, adminSetOrgCustomLimits, arg.OrganizationID, arg.CustomLimits)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const adminUpdatePlan = `-- name: AdminUpdatePlan :one
UPDATE plans SET name = $2, limits = $3 WHERE id = $1 RETURNING id, name, limits, created_at
`

type AdminUpdatePlanParams struct {
	ID     uuid.UUID       `json:"id"`
	Name   string          `json:"name"`
	Limits json.RawMessage `json:"limits"`
}

// A full replace (name + limits together), not a partial PATCH — mirrors
// the shape of POST /admin/plans, and a plan's whole point is that its
// limits are reviewed together, not merged field-by-field. 0 rows ->
// pgx.ErrNoRows -> admin.Service maps that to 404.
func (q *Queries) AdminUpdatePlan(ctx context.Context, arg AdminUpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, adminUpdatePlan, arg.ID, arg.Name, arg.Limits)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
	)
	return i, err
}
