// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auditlog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec
INSERT INTO audit_logs (organization_id, user_id, action, metadata)
VALUES ($1, $2, $3, $4)
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Action         string      `json:"action"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.Metadata,
	)
	return err
}

const queryAuditLogs = `-- name: QueryAuditLogs :many
SELECT id, organization_id, user_id, action, metadata, created_at FROM audit_logs
WHERE organization_id = $1
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR action = $3)
ORDER BY created_at DESC
LIMIT $4
`

type QueryAuditLogsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Action         *string     `json:"action"`
	Lim            int32       `json:"lim"`
}

func (q *Queries) QueryAuditLogs(ctx context.Context, arg QueryAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, queryAuditLogs,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
