// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: connectors.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countConnectorsByOrg = `-- name: CountConnectorsByOrg :one
SELECT count(*) FROM connectors WHERE organization_id = $1
`

func (q *Queries) CountConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectorsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConnector = `-- name: CreateConnector :one
INSERT INTO connectors (organization_id, name, type, encrypted_config)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at
`

type CreateConnectorParams struct {
	OrganizationID  uuid.UUID       `json:"organization_id"`
	Name            string          `json:"name"`
	Type            string          `json:"type"`
	EncryptedConfig json.RawMessage `json:"encrypted_config"`
}

func (q *Queries) CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, createConnector,
		arg.OrganizationID,
		arg.Name,
		arg.Type,
		arg.EncryptedConfig,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.EncryptedConfig,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnector = `-- name: DeleteConnector :execrows
DELETE FROM connectors WHERE id = $1 AND organization_id = $2
`

type DeleteConnectorParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteConnector(ctx context.Context, arg DeleteConnectorParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConnector, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getConnector = `-- name: GetConnector :one
SELECT id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at FROM connectors WHERE id = $1 AND organization_id = $2
`

type GetConnectorParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnector, arg.ID, arg.OrganizationID)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.EncryptedConfig,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConnectorByName = `-- name: GetConnectorByName :one
SELECT id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at FROM connectors WHERE organization_id = $1 AND name = $2
`

type GetConnectorByNameParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetConnectorByName(ctx context.Context, arg GetConnectorByNameParams) (Connector, error) {
	row := q.db.QueryRow(ctx, getConnectorByName, arg.OrganizationID, arg.Name)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.EncryptedConfig,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConnectorsByOrg = `-- name: ListConnectorsByOrg :many
SELECT id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at FROM connectors WHERE organization_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Connector, error) {
	rows, err := q.db.Query(ctx, listConnectorsByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Connector
	for rows.Next() {
		var i Connector
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Type,
			&i.EncryptedConfig,
			&i.Status,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnector = `-- name: UpdateConnector :one
UPDATE connectors
SET name = $3, status = $4, encrypted_config = $5, updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at
`

type UpdateConnectorParams struct {
	ID              uuid.UUID       `json:"id"`
	OrganizationID  uuid.UUID       `json:"organization_id"`
	Name            string          `json:"name"`
	Status          string          `json:"status"`
	EncryptedConfig json.RawMessage `json:"encrypted_config"`
}

func (q *Queries) UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (Connector, error) {
	row := q.db.QueryRow(ctx, updateConnector,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Status,
		arg.EncryptedConfig,
	)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.EncryptedConfig,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateConnectorHealth = `-- name: UpdateConnectorHealth :one
UPDATE connectors
SET status = $3, last_health_check_at = now(), updated_at = now()
WHERE id = $1 AND organization_id = $2
RETURNING id, organization_id, name, type, encrypted_config, status, last_health_check_at, created_at, updated_at
`

type UpdateConnectorHealthParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Status         string    `json:"status"`
}

func (q *Queries) UpdateConnectorHealth(ctx context.Context, arg UpdateConnectorHealthParams) (Connector, error) {
	row := q.db.QueryRow(ctx, updateConnectorHealth, arg.ID, arg.OrganizationID, arg.Status)
	var i Connector
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Type,
		&i.EncryptedConfig,
		&i.Status,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
