// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimPendingEmails = `-- name: ClaimPendingEmails :many
WITH due AS (
    SELECT id FROM email_outbox
    WHERE status = 'pending' AND next_attempt_at <= now()
    ORDER BY next_attempt_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
UPDATE email_outbox SET
    attempts = attempts + 1,
    next_attempt_at = now() + ($1::int * INTERVAL '1 second'),
    updated_at = now()
FROM due
WHERE email_outbox.id = due.id
RETURNING email_outbox.id, email_outbox.to_address, email_outbox.subject, email_outbox.body_html, email_outbox.body_text, email_outbox.status, email_outbox.attempts, email_outbox.last_error, email_outbox.next_attempt_at, email_outbox.sent_at, email_outbox.created_at, email_outbox.updated_at
`

type ClaimPendingEmailsParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

// Claims a batch by taking out a lease: attempts is incremented and
// next_attempt_at is pushed forward in the same statement, so a run that dies
// mid-send leaves rows that become claimable again on their own when the
// lease lapses -- no 'sending' status and no reaper job.
//
// The due set MUST be a CTE, not an `IN (SELECT ... LIMIT n FOR UPDATE SKIP
// LOCKED)` subquery. That subquery form is only correct when the planner
// materialises it; if it instead picks a re-evaluated SubPlan, every
// re-evaluation SKIPs the rows the previous one locked and returns a
// different set, so the UPDATE touches far more than batch_size rows. Which
// plan you get depends on table statistics and concurrent activity, so the
// subquery form passes on an idle table and fails under load -- verified
// against this table: it claimed 5 rows for a batch_size of 2. A CTE
// containing FOR UPDATE has side effects and is always materialised, so the
// lock-and-limit happens exactly once.
func (q *Queries) ClaimPendingEmails(ctx context.Context, arg ClaimPendingEmailsParams) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, claimPendingEmails, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailOutbox
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ToAddress,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueEmail = `-- name: EnqueueEmail :one
INSERT INTO email_outbox (to_address, subject, body_html, body_text)
VALUES ($1, $2, $3, $4)
RETURNING id, to_address, subject, body_html, body_text, status, attempts, last_error, next_attempt_at, sent_at, created_at, updated_at
`

type EnqueueEmailParams struct {
	ToAddress string  `json:"to_address"`
	Subject   string  `json:"subject"`
	BodyHtml  *string `json:"body_html"`
	BodyText  *string `json:"body_text"`
}

func (q *Queries) EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, enqueueEmail,
		arg.ToAddress,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
	)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, to_address, subject, body_html, body_text, status, attempts, last_error, next_attempt_at, sent_at, created_at, updated_at FROM email_outbox WHERE id = $1
`

func (q *Queries) GetEmailByID(ctx context.Context, id uuid.UUID) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, getEmailByID, id)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.ToAddress,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmailFailed = `-- name: MarkEmailFailed :exec
UPDATE email_outbox SET
    status = 'failed',
    last_error = $1,
    updated_at = now(),
    body_html = NULL,
    body_text = NULL
WHERE id = $2
`

type MarkEmailFailedParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

// Terminal: the attempt budget is spent. Bodies are dropped for the same
// reason as MarkEmailSent -- an undelivered token is no less live.
func (q *Queries) MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error {
	_, err := q.db.Exec(ctx, markEmailFailed, arg.LastError, arg.ID)
	return err
}

const markEmailSent = `-- name: MarkEmailSent :exec
UPDATE email_outbox SET
    status = 'sent',
    sent_at = now(),
    updated_at = now(),
    body_html = NULL,
    body_text = NULL,
    last_error = NULL
WHERE id = $1
`

// Nulls both bodies in the same statement that flips the status: a delivered
// verification body holds a live single-use token, and the row is kept for its
// audit value (recipient, subject, attempts), not for its content.
func (q *Queries) MarkEmailSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailSent, id)
	return err
}

const pruneEmailOutbox = `-- name: PruneEmailOutbox :execrows
DELETE FROM email_outbox
WHERE id IN (
    SELECT id FROM email_outbox
    WHERE status IN ('sent', 'failed')
      AND updated_at < now() - ($1::int * INTERVAL '1 second')
    LIMIT $2
)
`

type PruneEmailOutboxParams struct {
	RetentionSeconds int32 `json:"retention_seconds"`
	BatchSize        int32 `json:"batch_size"`
}

func (q *Queries) PruneEmailOutbox(ctx context.Context, arg PruneEmailOutboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneEmailOutbox, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rescheduleEmail = `-- name: RescheduleEmail :exec
UPDATE email_outbox SET
    last_error = $1,
    next_attempt_at = now() + ($2::int * INTERVAL '1 second'),
    updated_at = now()
WHERE id = $3
`

type RescheduleEmailParams struct {
	LastError      *string   `json:"last_error"`
	BackoffSeconds int32     `json:"backoff_seconds"`
	ID             uuid.UUID `json:"id"`
}

// A retryable failure: record why and push the next attempt out by the
// caller's backoff. Status stays 'pending' so the row is claimed again.
func (q *Queries) RescheduleEmail(ctx context.Context, arg RescheduleEmailParams) error {
	_, err := q.db.Exec(ctx, rescheduleEmail, arg.LastError, arg.BackoffSeconds, arg.ID)
	return err
}
