// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPKey = `-- name: CreateMCPKey :one
INSERT INTO mcp_api_keys (organization_id, user_id, name, key_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, user_id, name, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at
`

type CreateMCPKeyParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Name           string           `json:"name"`
	KeyHash        string           `json:"key_hash"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateMCPKey(ctx context.Context, arg CreateMCPKeyParams) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, createMCPKey,
		arg.OrganizationID,
		arg.UserID,
		arg.Name,
		arg.KeyHash,
		arg.ExpiresAt,
	)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPKeyByHash = `-- name: GetMCPKeyByHash :one
SELECT id, organization_id, user_id, name, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at FROM mcp_api_keys WHERE key_hash = $1
`

// Looks up a presented PAT by its SHA-256 hash (internal/middleware.RequireMCPKey).
// key_hash carries a unique index (migration 00008), so this is a single
// indexed read — no Redis cache in front of it, per Decision 1.
func (q *Queries) GetMCPKeyByHash(ctx context.Context, keyHash string) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, getMCPKeyByHash, keyHash)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMCPKeyByName = `-- name: GetMCPKeyByName :one
SELECT id, organization_id, user_id, name, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at FROM mcp_api_keys WHERE organization_id = $1 AND name = $2
`

type GetMCPKeyByNameParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
}

func (q *Queries) GetMCPKeyByName(ctx context.Context, arg GetMCPKeyByNameParams) (McpApiKey, error) {
	row := q.db.QueryRow(ctx, getMCPKeyByName, arg.OrganizationID, arg.Name)
	var i McpApiKey
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listMCPKeysByOrg = `-- name: ListMCPKeysByOrg :many
SELECT id, organization_id, user_id, name, key_hash, scopes, last_used_at, expires_at, revoked_at, created_at FROM mcp_api_keys WHERE organization_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListMCPKeysByOrg(ctx context.Context, organizationID uuid.UUID) ([]McpApiKey, error) {
	rows, err := q.db.Query(ctx, listMCPKeysByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpApiKey
	for rows.Next() {
		var i McpApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.KeyHash,
			&i.Scopes,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMCPKey = `-- name: RevokeMCPKey :execrows
UPDATE mcp_api_keys SET revoked_at = now() WHERE id = $1 AND organization_id = $2
`

type RevokeMCPKeyParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeMCPKey(ctx context.Context, arg RevokeMCPKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMCPKey, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const stampMCPKeyLastUsed = `-- name: StampMCPKeyLastUsed :exec
UPDATE mcp_api_keys SET last_used_at = now() WHERE id = $1
`

// Best-effort bookkeeping: called after a successful RequireMCPKey
// authentication. A failure to stamp must never fail the MCP request, so
// the caller logs and swallows any error from this query.
func (q *Queries) StampMCPKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, stampMCPKeyLastUsed, id)
	return err
}
