// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembershipsByOrg = `-- name: CountMembershipsByOrg :one
SELECT count(*) FROM memberships WHERE organization_id = $1
`

func (q *Queries) CountMembershipsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembershipsByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (user_id, organization_id, role)
VALUES ($1, $2, $3)
RETURNING id, user_id, organization_id, role, created_at
`

type CreateMembershipParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership, arg.UserID, arg.OrganizationID, arg.Role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE user_id = $1 AND organization_id = $2
`

type DeleteMembershipParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteMembership, arg.UserID, arg.OrganizationID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, user_id, organization_id, role, created_at FROM memberships
WHERE user_id = $1 AND organization_id = $2
`

type GetMembershipParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.OrganizationID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrganizationID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT
  m.id, m.user_id, m.organization_id, m.role, m.created_at,
  o.id   AS org_id,
  o.name AS org_name,
  o.slug AS org_slug,
  o.created_at AS org_created_at,
  o.updated_at AS org_updated_at
FROM memberships m
JOIN organizations o ON o.id = m.organization_id
WHERE m.user_id = $1
ORDER BY m.created_at ASC
`

type ListMembershipsByUserRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
	Role           string    `json:"role"`
	CreatedAt      time.Time `json:"created_at"`
	OrgID          uuid.UUID `json:"org_id"`
	OrgName        string    `json:"org_name"`
	OrgSlug        string    `json:"org_slug"`
	OrgCreatedAt   time.Time `json:"org_created_at"`
	OrgUpdatedAt   time.Time `json:"org_updated_at"`
}

func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembershipsByUserRow
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OrganizationID,
			&i.Role,
			&i.CreatedAt,
			&i.OrgID,
			&i.OrgName,
			&i.OrgSlug,
			&i.OrgCreatedAt,
			&i.OrgUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT
  m.user_id,
  u.email,
  u.display_name,
  m.role,
  m.created_at AS joined_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.created_at ASC
`

type ListOrganizationMembersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	DisplayName *string   `json:"display_name"`
	Role        string    `json:"role"`
	JoinedAt    time.Time `json:"joined_at"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationMembersRow
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
