// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getActivePlanPrice = `-- name: GetActivePlanPrice :one
SELECT id, plan_id, stripe_price_id, unit_amount, currency, interval, active, created_at FROM plan_prices
WHERE plan_id = $1
  AND currency = $2
  AND "interval" = $3
  AND active = true
ORDER BY created_at DESC
LIMIT 1
`

type GetActivePlanPriceParams struct {
	PlanID          uuid.UUID `json:"plan_id"`
	Currency        string    `json:"currency"`
	BillingInterval string    `json:"billing_interval"`
}

// Resolves the one Stripe Price a checkout should charge. Per plan decision
// 3 there is exactly one active THB monthly Price per plan today; currency
// and interval are parameters rather than constants so a second currency is
// a plan_prices row plus a Stripe Price, not a migration and not a query
// change. Newest-first so re-pricing a plan is "insert the new row, then
// deactivate the old one", with no window in which neither is selectable.
func (q *Queries) GetActivePlanPrice(ctx context.Context, arg GetActivePlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, getActivePlanPrice, arg.PlanID, arg.Currency, arg.BillingInterval)
	var i PlanPrice
	err := row.Scan(
		&i.ID,
		&i.PlanID,
		&i.StripePriceID,
		&i.UnitAmount,
		&i.Currency,
		&i.Interval,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, limits, created_at, stripe_product_id, is_public, sort_order FROM plans WHERE id = $1
`

// The tenant-facing twin of AdminGetPlanByID (queries/admin.sql), which is
// reachable only from the superadmin console. internal/module/billing needs
// to resolve the plan a checkout is for -- and to check is_public before
// selling it -- without reaching into an Admin*-prefixed query it is not
// entitled to use.
func (q *Queries) GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
		&i.StripeProductID,
		&i.IsPublic,
		&i.SortOrder,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, limits, created_at, stripe_product_id, is_public, sort_order FROM plans WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
		&i.StripeProductID,
		&i.IsPublic,
		&i.SortOrder,
	)
	return i, err
}

const getPlanByStripePriceID = `-- name: GetPlanByStripePriceID :one
SELECT p.id, p.name, p.limits, p.created_at, p.stripe_product_id, p.is_public, p.sort_order FROM plans p
JOIN plan_prices pp ON pp.plan_id = p.id
WHERE pp.stripe_price_id = $1::text
`

// Resolves the entitlement plan a Stripe Subscription is actually paying
// for, from the Price id on its line item. This is the webhook's PRIMARY
// plan resolution and metadata.plan_id is only the fallback, deliberately:
// the Customer Portal lets a customer switch plans without this application
// being involved, which changes the Price on the subscription but leaves
// the plan_id this code stamped into metadata at checkout time frozen at
// whatever they bought originally. Trusting metadata there would keep
// billing them for the new plan while entitling them to the old one.
//
// Not filtered on plan_prices.active: a plan re-priced after a customer
// subscribed leaves that customer on the old, now-inactive Price, and their
// renewal events must still resolve to the plan. `active` governs what may
// be SOLD (GetActivePlanPrice), not what an existing subscription means.
func (q *Queries) GetPlanByStripePriceID(ctx context.Context, stripePriceID string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByStripePriceID, stripePriceID)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Limits,
		&i.CreatedAt,
		&i.StripeProductID,
		&i.IsPublic,
		&i.SortOrder,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, limits, created_at, stripe_product_id, is_public, sort_order FROM plans ORDER BY created_at ASC
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Limits,
			&i.CreatedAt,
			&i.StripeProductID,
			&i.IsPublic,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlan = `-- name: UpsertPlan :exec
INSERT INTO plans (name, limits)
VALUES ($1, $2)
ON CONFLICT (name) DO NOTHING
`

type UpsertPlanParams struct {
	Name   string          `json:"name"`
	Limits json.RawMessage `json:"limits"`
}

func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) error {
	_, err := q.db.Exec(ctx, upsertPlan, arg.Name, arg.Limits)
	return err
}
