// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AdminCountActiveMCPKeys(ctx context.Context) (int64, error)
	AdminCountActiveSessions(ctx context.Context) (int64, error)
	AdminCountActiveSessionsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	AdminCountAllAuditLogs(ctx context.Context) (int64, error)
	AdminCountAllConnectors(ctx context.Context) (int64, error)
	AdminCountAllMCPKeys(ctx context.Context) (int64, error)
	// The remaining queries back GET /admin/system/stats. Each is cached
	// individually under its own fixed filter key (admin.Service.SystemStats) —
	// there is no user-supplied filter, but they still go through
	// admin.Service.cachedCount for the same "don't COUNT(*) on every staff
	// page load" reason as the paged lists above.
	AdminCountAllOrganizations(ctx context.Context) (int64, error)
	AdminCountAllUsers(ctx context.Context) (int64, error)
	// Mirrors AdminQueryAuditLogs's WHERE exactly.
	AdminCountAuditLogs(ctx context.Context, arg AdminCountAuditLogsParams) (int64, error)
	// Mirrors AdminListConnectors's WHERE exactly.
	AdminCountConnectors(ctx context.Context, arg AdminCountConnectorsParams) (int64, error)
	// A rising 'failed' count is the single best early warning that Resend or
	// the EMAIL_FROM domain is misconfigured (CLAUDE.md's Background worker
	// bullet).
	AdminCountEmailOutboxByStatus(ctx context.Context) ([]AdminCountEmailOutboxByStatusRow, error)
	// Mirrors AdminListMCPKeys's WHERE exactly.
	AdminCountMCPKeys(ctx context.Context, arg AdminCountMCPKeysParams) (int64, error)
	// Mirrors AdminListOrganizations's WHERE exactly — the pair behind
	// admin.Service.cachedCount for GET /admin/organizations.
	AdminCountOrganizations(ctx context.Context, search *string) (int64, error)
	AdminCountOrganizationsSince(ctx context.Context, since time.Time) (int64, error)
	// Backs the PLAN_IN_USE guard on plan delete. plans is referenced by
	// org_subscriptions.plan_id with ON DELETE no action (migration 00005), so
	// the database would reject the delete anyway — this check exists so the
	// API can return a real 409 instead of surfacing that constraint
	// violation as a 500.
	AdminCountSubscriptionsByPlan(ctx context.Context, planID uuid.UUID) (int64, error)
	// Mirrors AdminListUsers's WHERE exactly.
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	AdminCountUsersSince(ctx context.Context, since time.Time) (int64, error)
	// plans.name carries a UNIQUE constraint; a colliding name surfaces as a
	// raw constraint-violation error (500), the same tolerance
	// subscription.Service.AssignPlan documents for a nonexistent plan id —
	// neither the source app nor this one adds a dedicated
	// PLAN_NAME_TAKEN code for what is, in a 2-5 person staff console, a
	// typo caught on the next attempt.
	AdminCreatePlan(ctx context.Context, arg AdminCreatePlanParams) (Plan, error)
	// memberships/connectors/mcp_api_keys/org_subscriptions all cascade
	// (migrations 00002/00005/00007/00008); audit_logs.organization_id carries
	// no FK (00004), so audit rows deliberately survive the org — see
	// admin.Service.DeleteOrganization's doc comment. The caller has already
	// loaded the org (to check its slug against the confirmation field), so
	// there is no existence race worth an :execrows check here.
	AdminDeleteOrganization(ctx context.Context, id uuid.UUID) error
	// The caller has already loaded the plan (AdminGetPlanByID, for the 404
	// check) and confirmed no org_subscriptions row references it
	// (AdminCountSubscriptionsByPlan, for PLAN_IN_USE) before this runs.
	AdminDeletePlan(ctx context.Context, id uuid.UUID) error
	// Queries backing internal/module/admin, the cross-org platform staff
	// console (docs/11-admin-panel.md). Every query here deliberately has NO
	// organization_id predicate the way the tenant-facing queries do — that is
	// the whole point of /admin, not an oversight. See the module's own
	// doc comment for the authorization boundary (RequirePlatformRole, not
	// RequireOrg/RequirePermission).
	//
	// None of these ever select connectors.encrypted_config or
	// mcp_api_keys.key_hash; column lists are explicit rather than SELECT *
	// specifically to keep it that way as the schema evolves.
	AdminGetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	AdminGetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	// Cross-org connector metadata only — no encrypted_config column in this
	// SELECT, ever (docs/11-admin-panel.md §7). Also used, filtered by
	// organization_id alone, to populate the connector list nested in
	// GET /admin/organizations/:orgId (admin.Service.OrganizationDetail).
	AdminListConnectors(ctx context.Context, arg AdminListConnectorsParams) ([]AdminListConnectorsRow, error)
	// Cross-org MCP key metadata only — no key_hash column in this SELECT,
	// ever (docs/11-admin-panel.md §7). search matches the key's own name or
	// its owner's email. Also used, filtered by organization_id alone, to
	// populate the MCP key list nested in GET /admin/organizations/:orgId.
	AdminListMCPKeys(ctx context.Context, arg AdminListMCPKeysParams) ([]AdminListMCPKeysRow, error)
	// search matches name or slug (case-insensitive substring). member/
	// connector/mcp-key counts are correlated subqueries rather than a
	// three-way JOIN + GROUP BY, which would multiply the plan row per
	// member*connector*key combination. plan_name is NULL for an org with no
	// subscription row.
	AdminListOrganizations(ctx context.Context, arg AdminListOrganizationsParams) ([]AdminListOrganizationsRow, error)
	// search matches email or display_name. role is nullable text taking
	// 'superadmin', 'support', 'none' (meaning platform_role IS NULL), or NULL
	// (no filter) — a single text param rather than a separate bool so the
	// three-way choice stays one WHERE clause. banned is a nullable bool.
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	// LEFT JOIN so a plan with zero subscribers still shows a 0 row rather
	// than disappearing from the breakdown entirely.
	AdminPlanBreakdown(ctx context.Context) ([]AdminPlanBreakdownRow, error)
	// Cross-org: unlike QueryAuditLogs (internal/infra/database/queries/auditlog.sql),
	// which mandates organization_id as a tenant-isolation guarantee, this one
	// deliberately carries no such predicate — see admin.sql's file header.
	// Two queries, two guarantees; do not widen QueryAuditLogs to cover this.
	//
	// action_patterns is a nullable text[] of LIKE patterns: the handler turns
	// a bare action into a literal (with '%'/'_' escaped) and a trailing '*'
	// into a '<prefix>%' pattern, so "admin.*" matches by prefix while an exact
	// action matches by equality (LIKE with no wildcard characters behaves as
	// equality). `LIKE ANY (array)` matches if any pattern in the array
	// matches.
	//
	// from/to are nullable naive timestamps — audit_logs.created_at has no time
	// zone (see QueryAuditLogs's comment); callers must normalize any RFC3339
	// input to UTC before binding here, same as there.
	AdminQueryAuditLogs(ctx context.Context, arg AdminQueryAuditLogsParams) ([]AdminQueryAuditLogsRow, error)
	// The remaining queries back Phase 3's mutation routes
	// (docs/11-admin-panel.md, execution plan Phase 3). CountSuperadmins,
	// SetUserBan, SetUserPlatformRole, and RevokeAllUserSessions already exist
	// (queries/users.sql, queries/sessions.sql) and are reused as-is rather
	// than duplicated here.
	// Touches only org_subscriptions.custom_limits — deliberately narrower
	// than UpsertOrgSubscription (subscriptions.sql), which also rewrites
	// plan_id via a full upsert. $2 is nullable: NULL clears back to
	// plan-only limits. 0 rows affected means the organization has no
	// org_subscriptions row yet (no plan ever assigned) — admin.Service turns
	// that into a 404 rather than a silent no-op, since org_subscriptions.plan_id
	// is NOT NULL and there is nothing here to attach custom_limits to.
	AdminSetOrgCustomLimits(ctx context.Context, arg AdminSetOrgCustomLimitsParams) (int64, error)
	// A full replace (name + limits together), not a partial PATCH — mirrors
	// the shape of POST /admin/plans, and a plan's whole point is that its
	// limits are reviewed together, not merged field-by-field. 0 rows ->
	// pgx.ErrNoRows -> admin.Service maps that to 404.
	AdminUpdatePlan(ctx context.Context, arg AdminUpdatePlanParams) (Plan, error)
	AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) error
	// Records the org's lazily-created Stripe Customer (plan decision 4), and
	// is the Postgres half of billing's no-duplicate-Customer guarantee: the
	// "stripe_customer_id IS NULL" predicate makes the claim conditional, so
	// of two concurrent checkout attempts exactly one UPDATE matches a row and
	// the other returns zero rows (pgx.ErrNoRows) and re-reads the winner's id.
	//
	// Deliberately an UPDATE, never an upsert. Creating an org_subscriptions
	// row is subscription.Service.AssignPlan's job and nobody else's (plan
	// invariant 5); an org with no row yet resolves to "unlimited" through
	// EffectiveLimits, so inserting one here would silently change that org's
	// entitlements as a side effect of a billing click. Rows are created by
	// the webhook (step 7) when a subscription actually starts.
	ClaimOrgStripeCustomer(ctx context.Context, arg ClaimOrgStripeCustomerParams) (*string, error)
	// Claims a batch by taking out a lease: attempts is incremented and
	// next_attempt_at is pushed forward in the same statement, so a run that dies
	// mid-send leaves rows that become claimable again on their own when the
	// lease lapses -- no 'sending' status and no reaper job.
	//
	// The due set MUST be a CTE, not an `IN (SELECT ... LIMIT n FOR UPDATE SKIP
	// LOCKED)` subquery. That subquery form is only correct when the planner
	// materialises it; if it instead picks a re-evaluated SubPlan, every
	// re-evaluation SKIPs the rows the previous one locked and returns a
	// different set, so the UPDATE touches far more than batch_size rows. Which
	// plan you get depends on table statistics and concurrent activity, so the
	// subquery form passes on an idle table and fails under load -- verified
	// against this table: it claimed 5 rows for a batch_size of 2. A CTE
	// containing FOR UPDATE has side effects and is always materialised, so the
	// lock-and-limit happens exactly once.
	ClaimPendingEmails(ctx context.Context, arg ClaimPendingEmailsParams) ([]EmailOutbox, error)
	// Webhook idempotency (step 7 of
	// .claude/plans/2026-09-13-billing-and-usage-metering.md). Stripe retries,
	// so the same event id can arrive many times; the id is the primary key of
	// stripe_events (migration 00013), so the second delivery conflicts.
	//
	// ON CONFLICT DO NOTHING ... RETURNING makes "already processed" a
	// pgx.ErrNoRows rather than a driver-level unique-violation the caller
	// would have to sniff a SQLSTATE for -- and, crucially, it does NOT abort
	// the surrounding transaction the way a raised 23505 would.
	//
	// The claim is issued INSIDE the same transaction as the state change it
	// guards (billing.Service.reconcile). That ordering is the whole point: a
	// failure after the claim rolls the claim back too, so Stripe's retry
	// reprocesses the event instead of finding it marked handled and silently
	// doing nothing. Claim-then-process in separate transactions loses the
	// state change forever with no error anywhere.
	ClaimStripeEvent(ctx context.Context, arg ClaimStripeEventParams) (string, error)
	// Backs POST /admin/2fa/confirm: stamps confirmed_at and stores the ten
	// recovery-code hashes generated at confirm time (never at enroll time,
	// since enroll may be called repeatedly before a confirm ever lands).
	ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) error
	// The audit_logs side of the same cross-check. "Two independent counters
	// disagreeing is the detection mechanism" (plan's "the metering problem,
	// stated plainly") for the undercounting invariant 3 makes structural: a
	// dropped usage_events write (logged at error, internal/module/mcp's
	// recordUsage) or a dropped audit_logs write (best-effort,
	// auditlog.Service.Record) shows up here as nonzero drift rather than
	// silently. created_at has no time zone -- `since` must already be UTC wall
	// clock, matching every other naive-timestamp comparison in this codebase
	// (see auditlog.sql's QueryAuditLogs comment). Served by
	// idx_audit_logs_created_at (00011), which leads on created_at alone --
	// the same shape idx_audit_logs_organization_id_created_at (00009) cannot
	// serve since this query has no organization_id predicate.
	CountAuditLogsToolCalledSince(ctx context.Context, since time.Time) (int64, error)
	CountConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountMembershipsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	// Step 5 of docs/12-billing-and-metering.md (not yet written; see
	// .claude/plans/2026-09-13-billing-and-usage-metering.md): the current
	// tool-call count subscription.Service.EnforceLimit checks against
	// max_tool_calls_per_month before a tools/call dispatches
	// (internal/module/mcp/service.go). Counts usage_events directly rather
	// than reading usage_rollups, because the rollup for the current, still-open
	// month can be up to USAGE_ROLLUP_INTERVAL stale -- counting raw events
	// matches the cap's window exactly instead of undercounting by up to one
	// interval. Callers pass the start of the current UTC calendar month as
	// `since`, the same boundary internal/job/usagerollup buckets on
	// (date_trunc('month', occurred_at)), so the cap and the rollup agree on
	// what "this month" means. Served by
	// idx_usage_events_organization_id_occurred_at (00014), which leads on
	// organization_id -- unlike CountUsageEventsSince below, which has no
	// organization_id predicate and is served by the occurred_at-only index
	// instead.
	CountUsageEventsForOrgSince(ctx context.Context, arg CountUsageEventsForOrgSinceParams) (int64, error)
	// The usage_events side of the rollup job's audit_logs cross-check. Bounded
	// by the same `since` the rollup itself uses, and served by
	// idx_usage_events_occurred_at (00014) -- the same index the prune query
	// uses, both leading on occurred_at with no organization_id predicate.
	CountUsageEventsSince(ctx context.Context, since time.Time) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error)
	// scopes ($6) is nullable: a nil slice binds NULL (no independent
	// restriction, the key rides the creator's live grant), a non-empty slice
	// narrows it. mcpkey.Service.Create is responsible for never passing a
	// non-nil empty slice here — that would silently mint a key that permits
	// nothing.
	CreateMCPKey(ctx context.Context, arg CreateMCPKeyParams) (McpApiKey, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// One row per billable MCP tool call, written from the gateway's hot path
	// (internal/module/mcp/service.go) immediately alongside the mcp.tool.called
	// audit row -- see migration 00014's comment on usage_events. connector_id
	// and mcp_key_id are nullable FKs (ON DELETE SET NULL) so a later connector
	// or key deletion never erases the count it represents. quantity is not
	// taken as a parameter: it defaults to 1, matching "one row = one billable
	// tool call" -- this is never the rate limiter's N-upstream-request charge.
	CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConnector(ctx context.Context, arg DeleteConnectorParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeletePermissionsByRole(ctx context.Context, roleID uuid.UUID) error
	EnqueueEmail(ctx context.Context, arg EnqueueEmailParams) (EmailOutbox, error)
	// Maps a Stripe Customer back to its tenant. Backed by the partial unique
	// index idx_org_subscriptions_stripe_customer_id (migration 00013), so a
	// given customer id identifies exactly one organization -- which is what
	// makes it impossible for an event carrying org A's identifiers to land on
	// org B's row.
	FindOrgByStripeCustomerID(ctx context.Context, stripeCustomerID string) (uuid.UUID, error)
	// The subscription-id twin of FindOrgByStripeCustomerID, backed by
	// idx_org_subscriptions_stripe_subscription_id. Preferred over the customer
	// lookup when both are available: a Customer can in principle outlive and
	// outnumber its Subscriptions, while a Subscription belongs to exactly one.
	FindOrgByStripeSubscriptionID(ctx context.Context, stripeSubscriptionID string) (uuid.UUID, error)
	// Resolves the one Stripe Price a checkout should charge. Per plan decision
	// 3 there is exactly one active THB monthly Price per plan today; currency
	// and interval are parameters rather than constants so a second currency is
	// a plan_prices row plus a Stripe Price, not a migration and not a query
	// change. Newest-first so re-pricing a plan is "insert the new row, then
	// deactivate the old one", with no window in which neither is selectable.
	GetActivePlanPrice(ctx context.Context, arg GetActivePlanPriceParams) (PlanPrice, error)
	GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error)
	GetConnectorByName(ctx context.Context, arg GetConnectorByNameParams) (Connector, error)
	GetEmailByID(ctx context.Context, id uuid.UUID) (EmailOutbox, error)
	// Looks up a presented PAT by its SHA-256 hash (internal/middleware.RequireMCPKey).
	// key_hash carries a unique index (migration 00008), so this is a single
	// indexed read — no Redis cache in front of it, per Decision 1.
	//
	// Joined against users for owner_banned_at: an MCP PAT has no expiry of its
	// own, so a banned owner's key would otherwise keep authenticating forever
	// (docs/11-admin-panel.md §4). Extending this query rather than adding a
	// sibling keeps exactly one gateway auth path.
	GetMCPKeyByHash(ctx context.Context, keyHash string) (GetMCPKeyByHashRow, error)
	GetMCPKeyByName(ctx context.Context, arg GetMCPKeyByNameParams) (McpApiKey, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	// The billing module's (internal/module/billing) narrow read of an org's
	// Stripe linkage. Deliberately separate from GetOrgSubscription, which
	// exists to serve GET /subscription and whose row shape the frontend and
	// internal/module/admin both depend on -- widening it with Stripe columns
	// would push billing state into every caller of the entitlement read path.
	// Note what is NOT selected: custom_limits and plans.limits. Entitlement
	// resolution stays subscription.Service.EffectiveLimits' job alone
	// (plan invariant 1), and nothing here is allowed to become a second
	// answer to "what may this org do".
	GetOrgBillingRef(ctx context.Context, organizationID uuid.UUID) (GetOrgBillingRefRow, error)
	// The webhook's (internal/module/billing, step 7) read of everything it
	// needs to decide whether an incoming Stripe event is newer than what is
	// already stored, taken FOR UPDATE.
	//
	// FOR UPDATE, not a plain SELECT: two deliveries for the same organization
	// can be in flight at once (Stripe retries while the first attempt is still
	// running, or a subscription.updated and an invoice.paid arrive together).
	// Without the row lock both transactions would read the same watermark,
	// both would decide they are newer, and the older one could commit last.
	// The lock serializes them, so the "is this event stale" check and the
	// write that advances the watermark are one atomic step.
	//
	// Deliberately does not select custom_limits or plans.limits: entitlement
	// resolution is subscription.Service.EffectiveLimits' job alone (plan
	// invariant 1), and this must not become a second answer to "what may this
	// org do".
	GetOrgBillingSyncForUpdate(ctx context.Context, organizationID uuid.UUID) (GetOrgBillingSyncForUpdateRow, error)
	GetOrgSubscription(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionRow, error)
	GetOrgSubscriptionWithPlan(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionWithPlanRow, error)
	// The tenant-facing twin of AdminGetOrganizationByID (queries/admin.sql),
	// which is reachable only from the superadmin console. Added for
	// internal/module/billing, which names an org's lazily-created Stripe
	// Customer after the organization rather than after whichever member
	// happened to click "upgrade" first — a Stripe dashboard full of
	// personal names for company subscriptions is a support problem later.
	// Callers are already org-scoped by RequireOrg/RequirePermission before
	// this runs; it performs no authorization of its own.
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	// Resolves who to notify about an org-wide event (connector-health alerts
	// today). Membership.role is either set once at org creation ("owner",
	// organization.Service.Create) or validated to "admin"/"member" on invite
	// (organization.InviteRequest) -- an org always has exactly one owner row,
	// never zero or more than one.
	GetOrganizationOwner(ctx context.Context, organizationID uuid.UUID) (GetOrganizationOwnerRow, error)
	// The tenant-facing twin of AdminGetPlanByID (queries/admin.sql), which is
	// reachable only from the superadmin console. internal/module/billing needs
	// to resolve the plan a checkout is for -- and to check is_public before
	// selling it -- without reaching into an Admin*-prefixed query it is not
	// entitled to use.
	GetPlanByID(ctx context.Context, id uuid.UUID) (Plan, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	// Resolves the entitlement plan a Stripe Subscription is actually paying
	// for, from the Price id on its line item. This is the webhook's PRIMARY
	// plan resolution and metadata.plan_id is only the fallback, deliberately:
	// the Customer Portal lets a customer switch plans without this application
	// being involved, which changes the Price on the subscription but leaves
	// the plan_id this code stamped into metadata at checkout time frozen at
	// whatever they bought originally. Trusting metadata there would keep
	// billing them for the new plan while entitling them to the old one.
	//
	// Not filtered on plan_prices.active: a plan re-priced after a customer
	// subscribed leaves that customer on the old, now-inactive Price, and their
	// renewal events must still resolve to the plan. `active` governs what may
	// be SOLD (GetActivePlanPrice), not what an existing subscription means.
	GetPlanByStripePriceID(ctx context.Context, stripePriceID string) (Plan, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserTOTP(ctx context.Context, userID uuid.UUID) (UserTotp, error)
	ListConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Connector, error)
	// Cross-org sweep for the connector-health background job
	// (internal/job/connectorhealth) -- deliberately not organization-scoped,
	// unlike every other query in this file. encrypted_config is NOT selected:
	// the job re-reads and decrypts each connector through connector.Service so
	// decrypted config never leaves the service that owns it (CLAUDE.md).
	// Ordered oldest-checked-first (nulls, i.e. never checked, first) so a
	// backlog drains in the order it went stale rather than round-robining.
	ListConnectorsForHealthCheck(ctx context.Context, batchSize int32) ([]ListConnectorsForHealthCheckRow, error)
	ListMCPKeysByOrg(ctx context.Context, organizationID uuid.UUID) ([]McpApiKey, error)
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListPermissionActionsByUserOrg(ctx context.Context, arg ListPermissionActionsByUserOrgParams) ([]string, error)
	ListPermissionsByRoleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Permission, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListRolesByOrg(ctx context.Context, organizationID uuid.UUID) ([]Role, error)
	// Terminal: the attempt budget is spent. Bodies are dropped for the same
	// reason as MarkEmailSent -- an undelivered token is no less live.
	MarkEmailFailed(ctx context.Context, arg MarkEmailFailedParams) error
	// Nulls both bodies in the same statement that flips the status: a delivered
	// verification body holds a live single-use token, and the row is kept for its
	// audit value (recipient, subject, attempts), not for its content.
	MarkEmailSent(ctx context.Context, id uuid.UUID) error
	MarkUserVerified(ctx context.Context, id uuid.UUID) error
	PruneEmailOutbox(ctx context.Context, arg PruneEmailOutboxParams) (int64, error)
	// Deletes usage_events rows older than retention, batch-at-a-time like
	// PruneEmailOutbox (email_outbox.sql) and DeleteExpiredSessions
	// (sessions.sql). Deliberately has no organization_id predicate -- this is
	// the query idx_usage_events_occurred_at (00014) exists for; adding one
	// would defeat that index on this table, which is the largest in the
	// schema (one row per tool call).
	PruneUsageEvents(ctx context.Context, arg PruneUsageEventsParams) (int64, error)
	// actions is a nullable text[]: NULL (no ?action= given at all) matches
	// every row, same as before repeatable action filtering was added. An
	// empty (non-NULL) array must never reach this query — `action = ANY('{}')`
	// is always false and would silently return zero rows instead of
	// "unfiltered" — so callers must pass a nil slice, not an empty one, when
	// no action filter applies; see auditlog.Service.Query.
	//
	// since is a nullable timestamp (audit_logs.created_at has no time zone),
	// compared with >= so a since value equal to a row's created_at includes
	// that row (inclusive lower bound). Callers must normalize any RFC3339
	// input to UTC before binding it here, since the column stores naive
	// UTC wall-clock values.
	QueryAuditLogs(ctx context.Context, arg QueryAuditLogsParams) ([]AuditLog, error)
	// A retryable failure: record why and push the next attempt out by the
	// caller's backoff. Status stays 'pending' so the row is claimed again.
	RescheduleEmail(ctx context.Context, arg RescheduleEmailParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeMCPKey(ctx context.Context, arg RevokeMCPKeyParams) (int64, error)
	RevokeSessionByID(ctx context.Context, id uuid.UUID) error
	RevokeSessionFamily(ctx context.Context, family uuid.UUID) error
	// Folds usage_events into usage_rollups for every period whose bucket start
	// (UTC calendar month, date_trunc('month', occurred_at)) falls on or after
	// `since`. internal/job/usagerollup is the only caller, and it is the one
	// that must keep `since` inside the still-fully-present window -- see that
	// package's rollupLookbackMonths comment for why a re-aggregation must never
	// reach a period that a prior prune has partially emptied.
	//
	// The ON CONFLICT target is usage_rollups' natural key from migration 00014
	// (organization_id, period_start, tool) -- deliberately excluding
	// period_end, per that migration's comment -- so re-running this over the
	// same window is idempotent: it recomputes each period's true count from
	// usage_events and overwrites the existing rollup rather than adding to it.
	// reported_at is never set here (decision 1: a cap, not a charge -- nothing
	// is ever reported to Stripe from this table).
	RollupUsageEvents(ctx context.Context, since time.Time) (int64, error)
	// Both $2 and $3 are nullable; an unban passes NULL/NULL. users.banned_at
	// is the durable source of truth behind the Redis banned:<userId> cache
	// (see internal/infra/redis/auth.go and internal/middleware.Guards.verify).
	SetUserBan(ctx context.Context, arg SetUserBanParams) error
	// $2 is nullable: NULL revokes platform staff status (cmd/grantadmin's
	// "-role none"), 'superadmin'/'support' grants it. Enforced by the
	// users_platform_role_check CHECK constraint from migration 00011.
	SetUserPlatformRole(ctx context.Context, arg SetUserPlatformRoleParams) error
	// Best-effort bookkeeping: called after a successful RequireMCPKey
	// authentication. A failure to stamp must never fail the MCP request, so
	// the caller logs and swallows any error from this query.
	StampMCPKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (Connector, error)
	UpdateConnectorHealth(ctx context.Context, arg UpdateConnectorHealthParams) (Connector, error)
	// Writes the Stripe linkage columns of an org_subscriptions row that
	// already exists, plus the out-of-order watermark (stripe_event_at,
	// migration 00016).
	//
	// An UPDATE, never an upsert, and it touches neither plan_id nor
	// custom_limits. Creating the row and moving plan_id is
	// subscription.Service.AssignPlan's job and nobody else's (plan invariant
	// 5); custom_limits is the admin override that must survive a billing event
	// (invariant 2). What is left -- customer id, subscription id, status,
	// period end, cancellation flag -- is billing's own bookkeeping, the same
	// ownership ClaimOrgStripeCustomer already has over stripe_customer_id.
	//
	// Every value column is nullable-optional and COALESCEs to its current
	// value, because the handled events carry different subsets: a
	// checkout.session.completed knows the customer and subscription ids but
	// not the authoritative status (customer.subscription.created, arriving
	// alongside it, does), and an invoice.payment_failed knows the status but
	// not the period end. "Absent" must mean "leave alone", never "set to
	// NULL" -- otherwise each event would erase what the last one learned.
	//
	// clear_subscription is the one exception, and it is plan decision 4:
	// "stripe_subscription_id IS NULL" is the canonical "not paying" signal, so
	// a cancellation CLEARS the column rather than leaving it pointing at a
	// dead Stripe object.
	UpdateOrgStripeSubscription(ctx context.Context, arg UpdateOrgStripeSubscriptionParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Backs POST /admin/2fa/verify's recovery-code path: persists the
	// caller-supplied remaining set after one hash is removed, so a recovery
	// code is usable exactly once.
	UpdateUserTOTPRecoveryCodes(ctx context.Context, arg UpdateUserTOTPRecoveryCodesParams) error
	UpsertOrgSubscription(ctx context.Context, arg UpsertOrgSubscriptionParams) error
	UpsertPlan(ctx context.Context, arg UpsertPlanParams) error
	// Backs POST /admin/2fa/enroll (execution plan Task 6.3). Re-callable: a
	// staff member who lost their authenticator app before confirming (or
	// wants to re-enroll a new one) can call enroll again, which wipes any
	// prior confirmation and recovery codes along with the old secret -- an
	// unconfirmed or replaced secret must never leave a stale confirmed_at or
	// a set of recovery codes tied to a key that no longer exists.
	// recovery_codes is NOT NULL with no column default (migration 00012), so
	// every insert must supply '{}' explicitly here; confirm sets the real ten.
	UpsertUserTOTPSecret(ctx context.Context, arg UpsertUserTOTPSecretParams) error
}

var _ Querier = (*Queries)(nil)
