// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) error
	CountConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountMembershipsByOrg(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateConnector(ctx context.Context, arg CreateConnectorParams) (Connector, error)
	// scopes ($6) is nullable: a nil slice binds NULL (no independent
	// restriction, the key rides the creator's live grant), a non-empty slice
	// narrows it. mcpkey.Service.Create is responsible for never passing a
	// non-nil empty slice here — that would silently mint a key that permits
	// nothing.
	CreateMCPKey(ctx context.Context, arg CreateMCPKeyParams) (McpApiKey, error)
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (Membership, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteConnector(ctx context.Context, arg DeleteConnectorParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error)
	DeleteMembership(ctx context.Context, arg DeleteMembershipParams) error
	DeletePermissionsByRole(ctx context.Context, roleID uuid.UUID) error
	GetConnector(ctx context.Context, arg GetConnectorParams) (Connector, error)
	GetConnectorByName(ctx context.Context, arg GetConnectorByNameParams) (Connector, error)
	// Looks up a presented PAT by its SHA-256 hash (internal/middleware.RequireMCPKey).
	// key_hash carries a unique index (migration 00008), so this is a single
	// indexed read — no Redis cache in front of it, per Decision 1.
	GetMCPKeyByHash(ctx context.Context, keyHash string) (McpApiKey, error)
	GetMCPKeyByName(ctx context.Context, arg GetMCPKeyByNameParams) (McpApiKey, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (Membership, error)
	GetOrgSubscription(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionRow, error)
	GetOrgSubscriptionWithPlan(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionWithPlanRow, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListConnectorsByOrg(ctx context.Context, organizationID uuid.UUID) ([]Connector, error)
	ListMCPKeysByOrg(ctx context.Context, organizationID uuid.UUID) ([]McpApiKey, error)
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error)
	ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error)
	ListPermissionActionsByUserOrg(ctx context.Context, arg ListPermissionActionsByUserOrgParams) ([]string, error)
	ListPermissionsByRoleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Permission, error)
	ListPlans(ctx context.Context) ([]Plan, error)
	ListRolesByOrg(ctx context.Context, organizationID uuid.UUID) ([]Role, error)
	QueryAuditLogs(ctx context.Context, arg QueryAuditLogsParams) ([]AuditLog, error)
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeMCPKey(ctx context.Context, arg RevokeMCPKeyParams) (int64, error)
	RevokeSessionByID(ctx context.Context, id uuid.UUID) error
	RevokeSessionFamily(ctx context.Context, family uuid.UUID) error
	// Best-effort bookkeeping: called after a successful RequireMCPKey
	// authentication. A failure to stamp must never fail the MCP request, so
	// the caller logs and swallows any error from this query.
	StampMCPKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateConnector(ctx context.Context, arg UpdateConnectorParams) (Connector, error)
	UpdateConnectorHealth(ctx context.Context, arg UpdateConnectorHealthParams) (Connector, error)
	UpsertOrgSubscription(ctx context.Context, arg UpsertOrgSubscriptionParams) error
	UpsertPlan(ctx context.Context, arg UpsertPlanParams) error
}

var _ Querier = (*Queries)(nil)
