// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const assignMemberRole = `-- name: AssignMemberRole :exec
INSERT INTO member_roles (membership_id, role_id)
VALUES ($1, $2)
ON CONFLICT (membership_id, role_id) DO NOTHING
`

type AssignMemberRoleParams struct {
	MembershipID uuid.UUID `json:"membership_id"`
	RoleID       uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) error {
	_, err := q.db.Exec(ctx, assignMemberRole, arg.MembershipID, arg.RoleID)
	return err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (role_id, action)
VALUES ($1, $2)
`

type CreatePermissionParams struct {
	RoleID uuid.UUID `json:"role_id"`
	Action string    `json:"action"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission, arg.RoleID, arg.Action)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (organization_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, description, created_at
`

type CreateRoleParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.OrganizationID, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deletePermissionsByRole = `-- name: DeletePermissionsByRole :exec
DELETE FROM permissions WHERE role_id = $1
`

func (q *Queries) DeletePermissionsByRole(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermissionsByRole, roleID)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, organization_id, name, description, created_at FROM roles WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPermissionActionsByUserOrg = `-- name: ListPermissionActionsByUserOrg :many
SELECT DISTINCT p.action
FROM memberships m
JOIN member_roles mr ON mr.membership_id = m.id
JOIN roles r         ON r.id = mr.role_id
JOIN permissions p   ON p.role_id = r.id
WHERE m.user_id = $1 AND m.organization_id = $2
`

type ListPermissionActionsByUserOrgParams struct {
	UserID         uuid.UUID `json:"user_id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListPermissionActionsByUserOrg(ctx context.Context, arg ListPermissionActionsByUserOrgParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionActionsByUserOrg, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var action string
		if err := rows.Scan(&action); err != nil {
			return nil, err
		}
		items = append(items, action)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByRoleIDs = `-- name: ListPermissionsByRoleIDs :many
SELECT id, role_id, action, created_at FROM permissions
WHERE role_id = ANY($1::uuid[])
ORDER BY created_at ASC
`

func (q *Queries) ListPermissionsByRoleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, organization_id, name, description, created_at FROM roles
WHERE organization_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListRolesByOrg(ctx context.Context, organizationID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
