// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, family, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token, family, is_revoked, expires_at, created_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	Family       uuid.UUID `json:"family"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshToken,
		arg.Family,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.Family,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE id IN (
    SELECT id FROM sessions
    WHERE expires_at < now()
       OR (is_revoked = true AND created_at < now() - ($1::int * INTERVAL '1 second'))
    LIMIT $2
)
`

type DeleteExpiredSessionsParams struct {
	RetentionSeconds int32 `json:"retention_seconds"`
	BatchSize        int32 `json:"batch_size"`
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, family, is_revoked, expires_at, created_at FROM sessions WHERE refresh_token = $1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.Family,
		&i.IsRevoked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions SET is_revoked = true
WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions SET is_revoked = true WHERE id = $1
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, id)
	return err
}

const revokeSessionFamily = `-- name: RevokeSessionFamily :exec
UPDATE sessions SET is_revoked = true WHERE family = $1
`

func (q *Queries) RevokeSessionFamily(ctx context.Context, family uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSessionFamily, family)
	return err
}
