// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const claimOrgStripeCustomer = `-- name: ClaimOrgStripeCustomer :one
UPDATE org_subscriptions
SET stripe_customer_id = $1::text, updated_at = now()
WHERE organization_id = $2 AND stripe_customer_id IS NULL
RETURNING stripe_customer_id
`

type ClaimOrgStripeCustomerParams struct {
	StripeCustomerID string    `json:"stripe_customer_id"`
	OrganizationID   uuid.UUID `json:"organization_id"`
}

// Records the org's lazily-created Stripe Customer (plan decision 4), and
// is the Postgres half of billing's no-duplicate-Customer guarantee: the
// "stripe_customer_id IS NULL" predicate makes the claim conditional, so
// of two concurrent checkout attempts exactly one UPDATE matches a row and
// the other returns zero rows (pgx.ErrNoRows) and re-reads the winner's id.
//
// Deliberately an UPDATE, never an upsert. Creating an org_subscriptions
// row is subscription.Service.AssignPlan's job and nobody else's (plan
// invariant 5); an org with no row yet resolves to "unlimited" through
// EffectiveLimits, so inserting one here would silently change that org's
// entitlements as a side effect of a billing click. Rows are created by
// the webhook (step 7) when a subscription actually starts.
func (q *Queries) ClaimOrgStripeCustomer(ctx context.Context, arg ClaimOrgStripeCustomerParams) (*string, error) {
	row := q.db.QueryRow(ctx, claimOrgStripeCustomer, arg.StripeCustomerID, arg.OrganizationID)
	var stripe_customer_id *string
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const getOrgBillingRef = `-- name: GetOrgBillingRef :one
SELECT organization_id, plan_id, stripe_customer_id, stripe_subscription_id, status
FROM org_subscriptions
WHERE organization_id = $1
`

type GetOrgBillingRefRow struct {
	OrganizationID       uuid.UUID `json:"organization_id"`
	PlanID               uuid.UUID `json:"plan_id"`
	StripeCustomerID     *string   `json:"stripe_customer_id"`
	StripeSubscriptionID *string   `json:"stripe_subscription_id"`
	Status               *string   `json:"status"`
}

// The billing module's (internal/module/billing) narrow read of an org's
// Stripe linkage. Deliberately separate from GetOrgSubscription, which
// exists to serve GET /subscription and whose row shape the frontend and
// internal/module/admin both depend on -- widening it with Stripe columns
// would push billing state into every caller of the entitlement read path.
// Note what is NOT selected: custom_limits and plans.limits. Entitlement
// resolution stays subscription.Service.EffectiveLimits' job alone
// (plan invariant 1), and nothing here is allowed to become a second
// answer to "what may this org do".
func (q *Queries) GetOrgBillingRef(ctx context.Context, organizationID uuid.UUID) (GetOrgBillingRefRow, error) {
	row := q.db.QueryRow(ctx, getOrgBillingRef, organizationID)
	var i GetOrgBillingRefRow
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Status,
	)
	return i, err
}

const getOrgSubscription = `-- name: GetOrgSubscription :one
SELECT
  s.id, s.organization_id, s.plan_id, s.custom_limits, s.created_at, s.updated_at,
  p.id         AS plan_pid,
  p.name       AS plan_name,
  p.limits     AS plan_plimits,
  p.created_at AS plan_created_at
FROM org_subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.organization_id = $1
`

type GetOrgSubscriptionRow struct {
	ID             uuid.UUID       `json:"id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	PlanID         uuid.UUID       `json:"plan_id"`
	CustomLimits   []byte          `json:"custom_limits"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	PlanPid        uuid.UUID       `json:"plan_pid"`
	PlanName       string          `json:"plan_name"`
	PlanPlimits    json.RawMessage `json:"plan_plimits"`
	PlanCreatedAt  time.Time       `json:"plan_created_at"`
}

func (q *Queries) GetOrgSubscription(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscription, organizationID)
	var i GetOrgSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.CustomLimits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanPid,
		&i.PlanName,
		&i.PlanPlimits,
		&i.PlanCreatedAt,
	)
	return i, err
}

const getOrgSubscriptionWithPlan = `-- name: GetOrgSubscriptionWithPlan :one
SELECT s.custom_limits, p.limits AS plan_limits
FROM org_subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.organization_id = $1
`

type GetOrgSubscriptionWithPlanRow struct {
	CustomLimits []byte          `json:"custom_limits"`
	PlanLimits   json.RawMessage `json:"plan_limits"`
}

func (q *Queries) GetOrgSubscriptionWithPlan(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscriptionWithPlan, organizationID)
	var i GetOrgSubscriptionWithPlanRow
	err := row.Scan(&i.CustomLimits, &i.PlanLimits)
	return i, err
}

const upsertOrgSubscription = `-- name: UpsertOrgSubscription :exec
INSERT INTO org_subscriptions (organization_id, plan_id)
VALUES ($1, $2)
ON CONFLICT (organization_id)
DO UPDATE SET plan_id = EXCLUDED.plan_id, updated_at = now()
`

type UpsertOrgSubscriptionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	PlanID         uuid.UUID `json:"plan_id"`
}

func (q *Queries) UpsertOrgSubscription(ctx context.Context, arg UpsertOrgSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertOrgSubscription, arg.OrganizationID, arg.PlanID)
	return err
}
