// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const getOrgSubscription = `-- name: GetOrgSubscription :one
SELECT
  s.id, s.organization_id, s.plan_id, s.custom_limits, s.created_at, s.updated_at,
  p.id         AS plan_pid,
  p.name       AS plan_name,
  p.limits     AS plan_plimits,
  p.created_at AS plan_created_at
FROM org_subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.organization_id = $1
`

type GetOrgSubscriptionRow struct {
	ID             uuid.UUID       `json:"id"`
	OrganizationID uuid.UUID       `json:"organization_id"`
	PlanID         uuid.UUID       `json:"plan_id"`
	CustomLimits   []byte          `json:"custom_limits"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	PlanPid        uuid.UUID       `json:"plan_pid"`
	PlanName       string          `json:"plan_name"`
	PlanPlimits    json.RawMessage `json:"plan_plimits"`
	PlanCreatedAt  time.Time       `json:"plan_created_at"`
}

func (q *Queries) GetOrgSubscription(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscription, organizationID)
	var i GetOrgSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PlanID,
		&i.CustomLimits,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanPid,
		&i.PlanName,
		&i.PlanPlimits,
		&i.PlanCreatedAt,
	)
	return i, err
}

const getOrgSubscriptionWithPlan = `-- name: GetOrgSubscriptionWithPlan :one
SELECT s.custom_limits, p.limits AS plan_limits
FROM org_subscriptions s
JOIN plans p ON p.id = s.plan_id
WHERE s.organization_id = $1
`

type GetOrgSubscriptionWithPlanRow struct {
	CustomLimits []byte          `json:"custom_limits"`
	PlanLimits   json.RawMessage `json:"plan_limits"`
}

func (q *Queries) GetOrgSubscriptionWithPlan(ctx context.Context, organizationID uuid.UUID) (GetOrgSubscriptionWithPlanRow, error) {
	row := q.db.QueryRow(ctx, getOrgSubscriptionWithPlan, organizationID)
	var i GetOrgSubscriptionWithPlanRow
	err := row.Scan(&i.CustomLimits, &i.PlanLimits)
	return i, err
}

const upsertOrgSubscription = `-- name: UpsertOrgSubscription :exec
INSERT INTO org_subscriptions (organization_id, plan_id)
VALUES ($1, $2)
ON CONFLICT (organization_id)
DO UPDATE SET plan_id = EXCLUDED.plan_id, updated_at = now()
`

type UpsertOrgSubscriptionParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	PlanID         uuid.UUID `json:"plan_id"`
}

func (q *Queries) UpsertOrgSubscription(ctx context.Context, arg UpsertOrgSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertOrgSubscription, arg.OrganizationID, arg.PlanID)
	return err
}
