// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogsToolCalledSince = `-- name: CountAuditLogsToolCalledSince :one
SELECT count(*) FROM audit_logs
WHERE action = 'mcp.tool.called'
  AND created_at >= $1::timestamp
`

// The audit_logs side of the same cross-check. "Two independent counters
// disagreeing is the detection mechanism" (plan's "the metering problem,
// stated plainly") for the undercounting invariant 3 makes structural: a
// dropped usage_events write (logged at error, internal/module/mcp's
// recordUsage) or a dropped audit_logs write (best-effort,
// auditlog.Service.Record) shows up here as nonzero drift rather than
// silently. created_at has no time zone -- `since` must already be UTC wall
// clock, matching every other naive-timestamp comparison in this codebase
// (see auditlog.sql's QueryAuditLogs comment). Served by
// idx_audit_logs_created_at (00011), which leads on created_at alone --
// the same shape idx_audit_logs_organization_id_created_at (00009) cannot
// serve since this query has no organization_id predicate.
func (q *Queries) CountAuditLogsToolCalledSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsToolCalledSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageEventsSince = `-- name: CountUsageEventsSince :one
SELECT count(*) FROM usage_events
WHERE occurred_at >= $1::timestamp
`

// The usage_events side of the rollup job's audit_logs cross-check. Bounded
// by the same `since` the rollup itself uses, and served by
// idx_usage_events_occurred_at (00014) -- the same index the prune query
// uses, both leading on occurred_at with no organization_id predicate.
func (q *Queries) CountUsageEventsSince(ctx context.Context, since time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageEventsSince, since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUsageEvent = `-- name: CreateUsageEvent :exec
INSERT INTO usage_events (organization_id, connector_id, mcp_key_id, tool)
VALUES ($1, $2, $3, $4)
`

type CreateUsageEventParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	ConnectorID    pgtype.UUID `json:"connector_id"`
	McpKeyID       pgtype.UUID `json:"mcp_key_id"`
	Tool           string      `json:"tool"`
}

// One row per billable MCP tool call, written from the gateway's hot path
// (internal/module/mcp/service.go) immediately alongside the mcp.tool.called
// audit row -- see migration 00014's comment on usage_events. connector_id
// and mcp_key_id are nullable FKs (ON DELETE SET NULL) so a later connector
// or key deletion never erases the count it represents. quantity is not
// taken as a parameter: it defaults to 1, matching "one row = one billable
// tool call" -- this is never the rate limiter's N-upstream-request charge.
func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) error {
	_, err := q.db.Exec(ctx, createUsageEvent,
		arg.OrganizationID,
		arg.ConnectorID,
		arg.McpKeyID,
		arg.Tool,
	)
	return err
}

const pruneUsageEvents = `-- name: PruneUsageEvents :execrows
DELETE FROM usage_events
WHERE id IN (
    SELECT id FROM usage_events
    WHERE occurred_at < now() - ($1::int * INTERVAL '1 second')
    LIMIT $2
)
`

type PruneUsageEventsParams struct {
	RetentionSeconds int32 `json:"retention_seconds"`
	BatchSize        int32 `json:"batch_size"`
}

// Deletes usage_events rows older than retention, batch-at-a-time like
// PruneEmailOutbox (email_outbox.sql) and DeleteExpiredSessions
// (sessions.sql). Deliberately has no organization_id predicate -- this is
// the query idx_usage_events_occurred_at (00014) exists for; adding one
// would defeat that index on this table, which is the largest in the
// schema (one row per tool call).
func (q *Queries) PruneUsageEvents(ctx context.Context, arg PruneUsageEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneUsageEvents, arg.RetentionSeconds, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rollupUsageEvents = `-- name: RollupUsageEvents :execrows
INSERT INTO usage_rollups (organization_id, period_start, period_end, tool, call_count)
SELECT
    organization_id,
    date_trunc('month', occurred_at) AS period_start,
    date_trunc('month', occurred_at) + INTERVAL '1 month' AS period_end,
    tool,
    count(*) AS call_count
FROM usage_events
WHERE occurred_at >= $1::timestamp
GROUP BY organization_id, date_trunc('month', occurred_at), tool
ON CONFLICT (organization_id, period_start, tool)
DO UPDATE SET
    call_count = EXCLUDED.call_count,
    period_end = EXCLUDED.period_end
`

// Folds usage_events into usage_rollups for every period whose bucket start
// (UTC calendar month, date_trunc('month', occurred_at)) falls on or after
// `since`. internal/job/usagerollup is the only caller, and it is the one
// that must keep `since` inside the still-fully-present window -- see that
// package's rollupLookbackMonths comment for why a re-aggregation must never
// reach a period that a prior prune has partially emptied.
//
// The ON CONFLICT target is usage_rollups' natural key from migration 00014
// (organization_id, period_start, tool) -- deliberately excluding
// period_end, per that migration's comment -- so re-running this over the
// same window is idempotent: it recomputes each period's true count from
// usage_events and overwrites the existing rollup rather than adding to it.
// reported_at is never set here (decision 1: a cap, not a charge -- nothing
// is ever reported to Stripe from this table).
func (q *Queries) RollupUsageEvents(ctx context.Context, since time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, rollupUsageEvents, since)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
