// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_totp.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const confirmUserTOTP = `-- name: ConfirmUserTOTP :exec
UPDATE user_totp SET confirmed_at = now(), recovery_codes = $2 WHERE user_id = $1
`

type ConfirmUserTOTPParams struct {
	UserID        uuid.UUID `json:"user_id"`
	RecoveryCodes []string  `json:"recovery_codes"`
}

// Backs POST /admin/2fa/confirm: stamps confirmed_at and stores the ten
// recovery-code hashes generated at confirm time (never at enroll time,
// since enroll may be called repeatedly before a confirm ever lands).
func (q *Queries) ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) error {
	_, err := q.db.Exec(ctx, confirmUserTOTP, arg.UserID, arg.RecoveryCodes)
	return err
}

const getUserTOTP = `-- name: GetUserTOTP :one
SELECT user_id, secret_encrypted, recovery_codes, confirmed_at, created_at FROM user_totp WHERE user_id = $1
`

func (q *Queries) GetUserTOTP(ctx context.Context, userID uuid.UUID) (UserTotp, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, userID)
	var i UserTotp
	err := row.Scan(
		&i.UserID,
		&i.SecretEncrypted,
		&i.RecoveryCodes,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserTOTPRecoveryCodes = `-- name: UpdateUserTOTPRecoveryCodes :exec
UPDATE user_totp SET recovery_codes = $2 WHERE user_id = $1
`

type UpdateUserTOTPRecoveryCodesParams struct {
	UserID        uuid.UUID `json:"user_id"`
	RecoveryCodes []string  `json:"recovery_codes"`
}

// Backs POST /admin/2fa/verify's recovery-code path: persists the
// caller-supplied remaining set after one hash is removed, so a recovery
// code is usable exactly once.
func (q *Queries) UpdateUserTOTPRecoveryCodes(ctx context.Context, arg UpdateUserTOTPRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTPRecoveryCodes, arg.UserID, arg.RecoveryCodes)
	return err
}

const upsertUserTOTPSecret = `-- name: UpsertUserTOTPSecret :exec
INSERT INTO user_totp (user_id, secret_encrypted, recovery_codes)
VALUES ($1, $2, '{}')
ON CONFLICT (user_id) DO UPDATE
  SET secret_encrypted = $2, recovery_codes = '{}', confirmed_at = NULL
`

type UpsertUserTOTPSecretParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	SecretEncrypted json.RawMessage `json:"secret_encrypted"`
}

// Backs POST /admin/2fa/enroll (execution plan Task 6.3). Re-callable: a
// staff member who lost their authenticator app before confirming (or
// wants to re-enroll a new one) can call enroll again, which wipes any
// prior confirmation and recovery codes along with the old secret -- an
// unconfirmed or replaced secret must never leave a stale confirmed_at or
// a set of recovery codes tied to a key that no longer exists.
// recovery_codes is NOT NULL with no column default (migration 00012), so
// every insert must supply '{}' explicitly here; confirm sets the real ten.
func (q *Queries) UpsertUserTOTPSecret(ctx context.Context, arg UpsertUserTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, upsertUserTOTPSecret, arg.UserID, arg.SecretEncrypted)
	return err
}
